# Generated by Django 3.0.3 on 2020-04-06 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True)),
                ('price_datetime', models.DateTimeField(blank=True, null=True)),
                ('status_datetime', models.DateTimeField(blank=True, null=True)),
                ('sell_count', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'device_detail',
                'managed': False,
            },
        ),
    ]
