# Generated by Django 3.0.3 on 2020-04-06 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='media/person/')),
                ('created_at', models.DateTimeField(editable=False)),
                ('updated_at', models.DateTimeField(editable=False)),
                ('deleted_at', models.DateTimeField(editable=False)),
            ],
            options={
                'db_table': 'person',
                'managed': False,
            },
        ),
    ]
