# Generated by Django 3.0.3 on 2020-04-06 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_type', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='vehicletype',
            table='vehicle_type',
        ),
    ]
